version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=LukaM1999_fishing-booker

orbs:
  heroku: circleci/heroku@1.2.6
  sonarcloud: sonarsource/sonarcloud@1.0.3
workflows:
  heroku_deploy:
    jobs:
      - build-and-test
      - heroku/deploy-via-git:
          requires:
            - build-and-test